### ISSUE TITLE
Minor comment error?

### ISSUE THREAD

**Issue by yjchoi1** [geoelements/gns#22]
In the following lines, https://github.com/geoelements/gns/blob/ec49e2ab100b73ef2908ac77e1cb610e2c72cf20/gns/learned_simulator.py#L204  https://github.com/geoelements/gns/blob/ec49e2ab100b73ef2908ac77e1cb610e2c72cf20/gns/learned_simulator.py#L234, 
the dimension `(nparticles, dim)`  seems to be `(nparticle, 6, dim)`.

**Comment by kks32** [comment]
Yes, that makes sense, because it's a sequence of positions of the last 5 time steps
