### ISSUE TITLE
Argument missing in `train.py`

### ISSUE THREAD

**Issue by yjchoi1** [geoelements/gns#32]
**Describe the bug**
In [`train.py`](https://github.com/geoelements/gns/blob/e50a8d9d40de1d80f36364850928f8b58e6a5694/gns/render_rollout.py#L79), arguments for `train(simulator)` mismatch for the current train function `train(rank, flags, world_size)`. 

**To Reproduce**
1. OS/Platform: Linux
2. Run on '....': TACC gpu-a100
3. On condition '....': It occurs when the `model_file` does not exist for `python3 -m gns.train --mode='rollout' --data_path="${WORK_DIR}/datasets/${DATASET_NAME}/" --model_path="${WORK_DIR}/models/${DATASET_NAME}/" --model_file="model.pt" --train_state_file="train_state.pt" --output_path="${WORK_DIR}/rollouts"`
4. See error: missing arguments

**Expected behavior**

**Screenshots**

**Runtime environment (please complete the following information):**
 - OS/Docker image:
 - Branch [e.g. develop]: main

**Additional context**

**Comment by kks32** [comment]
@yjchoi1 Is this problem still there?
