### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by WPettersson** [geoelements/gns#33]
Hello Krishna et al.,

Thank you for your submission to JOSS, I'm happy for the opportunity to review it. I'll use this issue as a meta-issue to track my commentary. I'll be raising other issues (and mentioning them here) for specific items I note as I review the paper and software.

- [x] #34 
- [x] #35
- [x] #40 
- [x] #41
William

**Comment by osorensen** [comment]
Nice to see that you opened issues here @WPettersson. I just add a link to the review here so we keep track: https://github.com/openjournals/joss-reviews/issues/5025

**Comment by kks32** [comment]
Thanks @WPettersson and @osorensen I'm working on fixing them. Will do it ASAP.

**Comment by WPettersson** [comment]
All fixed, as far as I'm concerned. Well done on a nice job :)
