### ISSUE TITLE
Missing installation instructions for non-TACC users

### ISSUE THREAD

**Issue by WPettersson** [geoelements/gns#34]
Your README file includes details on how to install/use gns on TACC, but doesn't have information for people who won't be using TACC. It might be very hard to write a singular script to handle all cases, but it would be good to at least have a list of required packages (preferably with a link on where to find them) and compatible version numbers. For instance, the `build_venv.sh` file pulls in cuda 11.3 - will other versions work? It's okay to say "we don't know" if you don't know, but it's helpful to also point out that it is meant to work with 11.3.

**Comment by kks32** [comment]
Thanks @WPettersson. PyTorch Geometric and CUDA have only specific compatibilites as shown here
https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#quick-start

<img width="755" alt="image" src="https://user-images.githubusercontent.com/3963513/211033364-d9936ad3-0930-4594-9bf7-e4bf3f601cec.png">

We could add a similar table in the README to help users with installation on GPU machines.

**Comment by WPettersson** [comment]
An even easier solution would be to simply link to those instructions with a sentence like "GNS uses pytorch geometric and CUDA. These packages have specific requirements, please see <link> for details on installing pytorch-geometric."

**Comment by osorensen** [comment]
Nice to see that you opened issues here @WPettersson. I just add a link to the review here so we keep track: https://github.com/openjournals/joss-reviews/issues/5025
