### ISSUE TITLE
metadata in GNS

### ISSUE THREAD

**Issue by ZhangWenKang1** [geoelements/gns#76]
Hello, I want to know how vel_mean, vel_std, acc_mean, and acc_std are calculated in metadata? I used one of the datasets and used the sequence of positions in one of the segments to calculate mean and std, but the calculations were much different from those in metadata。
### For example, I calculated a piece of data under WaterDropSample:
  "vel_mean": [
    -0.00011191196940182947,
    -0.00027971224494040416
  ],
  "vel_std": [
    0.0013911897020589552,
    0.001303799159357853
  ]，
  "acc_mean": [
    -2.5874958351066937e-07,
    1.0644470675986365e-08
  ],
  "acc_std": [
    7.254938504794328e-05,
    9.334071443185402e-05
  ],
### But the original one was：
  "vel_mean": [
    -3.964619574176163e-05,
    -0.00026272129664401046
  ],
  "vel_std": [
    0.0013722809722366911,
    0.0013119977252142715
  ]，
  "acc_mean": [
    2.602686518497945e-08,
    1.0721623948191945e-07
  ],
  "acc_std": [
    6.742962470925277e-05,
    8.700719180424815e-05
  ],

### The calculation method is as follows：
```
import numpy as np

ac = np.load('train.npz', allow_pickle=True)

running_sum = dict(velocity_x=0, velocity_y=0, acceleration_x=0, acceleration_y=0)
running_sumsq = dict(velocity_x=0, velocity_y=0, acceleration_x=0, acceleration_y=0)
running_count = dict(velocity_x=0, velocity_y=0, acceleration_x=0, acceleration_y=0)

for nth_trajectory, directory in enumerate(ac):
    positions = ac[directory][0]
    # print(positions, positions.shape)
    dt = 1

    # compute velocities using finite difference
    # assume velocities before zero are equal to zero
    velocities = np.empty_like(positions)
    velocities[1:] = (positions[1:] - positions[:-1]) / dt
    velocities[0] = 0

    # compute accelerations finite difference
    # assume accelerations before zero are equal to zero
    accelerations = np.empty_like(velocities)
    accelerations[1:] = (velocities[1:] - velocities[:-1]) / dt
    accelerations[0] = 0

    # update variables for on-line mean and standard deviation calculation.
    for key in running_sum:
        if key == "velocity_x":
            data = velocities[:, :, 0]
        elif key == "velocity_y":
            data = velocities[:, :, 1]
        elif key == "velocity_z":
            data = velocities[:, :, 2]
        elif key == "acceleration_x":
            data = accelerations[:, :, 0]
        elif key == "acceleration_y":
            data = accelerations[:, :, 1]
        elif key == "acceleration_z":
            data = accelerations[:, :, 2]
        else:
            raise KeyError
        running_sum[key] += np.sum(data)
        running_sumsq[key] += np.sum(data ** 2)
        running_count[key] += np.size(data)

for key in running_sum:
    mean = running_sum[key] / running_count[key]
    std = np.sqrt((running_sumsq[key] - running_sum[key] ** 2 / running_count[key]) / (running_count[key] - 1))
    print(f"  {key}: mean={mean}, std={std}")
```

I don't know where my calculation went wrong.

**Comment by kks32** [comment]
@yjchoi1 Could you please look into this?

**Comment by yjchoi1** [comment]
I believe the reason for the difference is that the original metadata that you mentioned refers to the original `WaterDrop` data (link) but what you computed refers to the `WaterDropSample`, which is sampled from the original `WaterDrop`. So, it is just a problem of what data is used.

Here is an example for computing the statistics. Note that, for a large dataset, you may need to use the running sum to avoid excessive memory occupation. 

```
# Assuming trajectories is your dictionary of velocity arrays
trajectories = {
    'trajectory-1': velocity1,
    'trajectory-2': velocity2,
    ...
}

# Concatenate all velocity arrays along the time axis to get the shape (n_trajectories * n_timesteps, n_particles, n_dims)
all_velocities = np.concatenate(list(trajectories.values()), axis=0)  # Shape: (n_trajectories * n_timesteps, n_particles, n_dims)

# Compute mean and std over the concatenated time axis (axis=0)
mean_velocity = np.mean(all_velocities, axis=0)
std_velocity = np.std(all_velocities, axis=0)
```
