### ISSUE TITLE
how to download the "Cylinder flow with graph neural network-based simulator"?

### ISSUE THREAD

**Issue by freebob** [geoelements/gns#93]
I am currently working with the project and followed the instructions provided in the repository. However, I am unable to access the training data through the provided link: [[Link to Data](https://www.designsafe-ci.org/data/browser/public/designsafe.storage.published/PRJ-4000)]. Unfortunately, I encountered issues registering for an account needed to access the data.
Could you please guide me on how to obtain the training data? Any additional instructions or alternative links would be greatly appreciated.

Thank you for your assistance!

**Comment by freebob** [comment]
I got it, https://github.com/google-deepmind/deepmind-research/tree/master/meshgraphnets

**Comment by kks32** [comment]
https://www.designsafe-ci.org/data/browser/public/designsafe.storage.published/PRJ-4000

**Comment by freebob** [comment]
> https://www.designsafe-ci.org/data/browser/public/designsafe.storage.published/PRJ-4000

Thank you very much for your response and for the help you’ve provided.

However, I’ve encountered an issue as shown in the attached image. I’m facing some difficulties with registering my account and applying for access permissions, and I’m unsure about how to proceed. Could you kindly advise on the next steps? Additionally, is there an alternative way to access the dataset?
![ques](https://github.com/user-attachments/assets/86fcc4bb-e917-40b9-a93e-5b04c5dcf79a)

**Comment by kks32** [comment]
You will be able to download the data without logging in. The onboarding shouldn't take more than a day. So please let me know if there are any issues.

**Comment by freebob** [comment]
![image](https://github.com/user-attachments/assets/0ebd8471-2e20-4fa6-9a18-9e79d8b304e7)
Thank you for your response.

I was able to download test.npz and valid.npz without any issues. However, since the train.npz file exceeds 2GB, it requires account registration. This has led to the following issue, as shown below.

Additionally, I noticed that the onboarding process, which was mentioned to take no more than a day, has already taken over four days. Could you kindly advise on how to resolve this?
